name: Deploy React Build to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Push build folder to `build` branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build # branch to push to
          folder: dist # folder to push

      - name: Trigger Hostinger Auto-Deploy
        run: curl -X POST https://webhooks.hostinger.com/deploy/a6acd4c0e5ae9d80dbe3a1083b761f62
